.TH "Attribute" 3 "Mon May 27 2019" "MiniSQL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Attribute
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBid\fP"
.br
.ti -1c
.RI "int \fBtype\fP"
.br
.ti -1c
.RI "std::string \fBcolumn_name\fP"
.br
.ti -1c
.RI "std::string \fBcomment\fP"
.br
.ti -1c
.RI "\fBAuthorization\fP \fBauthorization\fP"
.br
.ti -1c
.RI "\fBFileId\fP \fBfile\fP"
.br
.ti -1c
.RI "\fBPageId\fP \fBfirst_page\fP"
.br
.ti -1c
.RI "\fBPageId\fP \fBfirst_index\fP"
.br
.ti -1c
.RI "bool \fBnullable\fP"
.br
.ti -1c
.RI "bool \fBis_primary_key\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 31 of file attribute\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MiniSQL from the source code\&.
