.TH "BinOpClause" 3 "Mon May 27 2019" "MiniSQL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BinOpClause
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBType\fP { \fBkOr\fP, \fBkAnd\fP }"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBConditionClause\fP * \fBlhs\fP"
.br
.ti -1c
.RI "\fBConditionClause\fP * \fBrhs\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 98 of file attribute\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MiniSQL from the source code\&.
