.TH "BufferManager::PagePiggyback" 3 "Mon May 27 2019" "MiniSQL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BufferManager::PagePiggyback
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBFileInfo\fP * \fBfinfo\fP"
.br
.ti -1c
.RI "\fBPageId\fP \fBpage_id\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 590 of file buffer\-manager\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MiniSQL from the source code\&.
