.TH "ColumnName" 3 "Mon May 27 2019" "MiniSQL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ColumnName
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const std::string & \fBdb_name\fP"
.br
.ti -1c
.RI "const std::string & \fBtable_name\fP"
.br
.ti -1c
.RI "const std::string & \fBcolumn_name\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 4 of file catalog\-manager\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MiniSQL from the source code\&.
