.TH "ItemPayload" 3 "Mon May 27 2019" "MiniSQL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ItemPayload
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBBufferManager::Iterator\fP< char > \fBtarget\fP"
.br
.ti -1c
.RI "const char * \fBdata\fP"
.br
.ti -1c
.RI "int \fBsize_by_bytes\fP"
.br
.ti -1c
.RI "bool \fBis_variadic\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 13 of file attribute\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MiniSQL from the source code\&.
