.TH "RangeClause" 3 "Mon May 27 2019" "MiniSQL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RangeClause
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBConditionClause\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBTest\fP (\fBISQLData\fP *data)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBAttribute\fP * \fBtarget\fP"
.br
.ti -1c
.RI "\fBISQLData\fP * \fBlower_bound\fP"
.br
.ti -1c
.RI "\fBISQLData\fP * \fBupper_bound\fP"
.br
.ti -1c
.RI "bool \fBis_not\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 109 of file attribute\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MiniSQL from the source code\&.
