.TH "ReportMsg" 3 "Mon May 27 2019" "MiniSQL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ReportMsg
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBdetail\fP"
.br
.ti -1c
.RI "int \fBcode\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 67 of file attribute\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MiniSQL from the source code\&.
