.TH "SetClause" 3 "Mon May 27 2019" "MiniSQL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SetClause
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBConditionClause\fP\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::set< \fBISQLData\fP * > \fBset\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 126 of file attribute\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MiniSQL from the source code\&.
