.TH "SQLBigInt" 3 "Mon May 27 2019" "MiniSQL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SQLBigInt
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBISQLNumber\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "int \fBCompare\fP (const \fBISQLData\fP *rhs) const override"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 251 of file sqldata\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MiniSQL from the source code\&.
