.TH "SQLNumericStruct" 3 "Mon May 27 2019" "MiniSQL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SQLNumericStruct
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum { \fBkMaxNumericLen\fP = 16 }"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned char \fBprecision\fP"
.br
.ti -1c
.RI "char \fBscale\fP"
.br
.ti -1c
.RI "unsigned char \fBsign\fP"
.br
.ti -1c
.RI "unsigned char \fBval\fP [kMaxNumericLen]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 121 of file sqldata\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MiniSQL from the source code\&.
