.TH "SQLTimeStruct" 3 "Mon May 27 2019" "MiniSQL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SQLTimeStruct
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBoperator==\fP (const \fBSQLTimeStruct\fP &rhs) const"
.br
.ti -1c
.RI "bool \fBoperator<\fP (const \fBSQLTimeStruct\fP &rhs) const"
.br
.ti -1c
.RI "bool \fBoperator>\fP (const \fBSQLTimeStruct\fP &rhs) const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned short \fBhour\fP"
.br
.ti -1c
.RI "unsigned short \fBminute\fP"
.br
.ti -1c
.RI "unsigned short \fBsecond\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 63 of file sqldata\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MiniSQL from the source code\&.
