.TH "SQLTypeID< SQLDouble >" 3 "Mon May 27 2019" "MiniSQL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SQLTypeID< SQLDouble >
.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static constexpr int \fBvalue\fP = 3"
.br
.ti -1c
.RI "static constexpr const char * \fBname\fP = 'double'"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<>
.br
struct SQLTypeID< SQLDouble >"

.PP
Definition at line 415 of file sqldata\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MiniSQL from the source code\&.
