.TH "SQLTypeID< T >" 3 "Mon May 27 2019" "MiniSQL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SQLTypeID< T >
.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static constexpr int \fBvalue\fP = \-1"
.br
.ti -1c
.RI "static constexpr char * \fBname\fP = 'invalid_type'"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename T>
.br
struct SQLTypeID< T >"

.PP
Definition at line 390 of file sqldata\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MiniSQL from the source code\&.
