var annotated_dup =
[
    [ "AliasedTableName", "struct_aliased_table_name.html", "struct_aliased_table_name" ],
    [ "Attribute", "struct_attribute.html", "struct_attribute" ],
    [ "Authorization", "struct_authorization.html", "struct_authorization" ],
    [ "BinOpClause", "struct_bin_op_clause.html", "struct_bin_op_clause" ],
    [ "BufferManager", "class_buffer_manager.html", "class_buffer_manager" ],
    [ "CatalogManager", "class_catalog_manager.html", "class_catalog_manager" ],
    [ "ColumnName", "struct_column_name.html", "struct_column_name" ],
    [ "Condition", "struct_condition.html", null ],
    [ "ConditionClause", "class_condition_clause.html", null ],
    [ "DataPage", "class_data_page.html", null ],
    [ "FStream", "class_f_stream.html", "class_f_stream" ],
    [ "GenericIOId", "struct_generic_i_o_id.html", "struct_generic_i_o_id" ],
    [ "IConstSQLDataVisitor", "class_i_const_s_q_l_data_visitor.html", null ],
    [ "IndexManager", "class_index_manager.html", "class_index_manager" ],
    [ "ISQLData", "class_i_s_q_l_data.html", "class_i_s_q_l_data" ],
    [ "ISQLDataVisitor", "class_i_s_q_l_data_visitor.html", null ],
    [ "ISQLNumber", "class_i_s_q_l_number.html", "class_i_s_q_l_number" ],
    [ "ISQLTimeOrDate", "class_i_s_q_l_time_or_date.html", "class_i_s_q_l_time_or_date" ],
    [ "ItemPayload", "struct_item_payload.html", "struct_item_payload" ],
    [ "MetaData", "struct_meta_data.html", "struct_meta_data" ],
    [ "MetaPage", "class_meta_page.html", null ],
    [ "Page", "struct_page.html", "struct_page" ],
    [ "RangeClause", "struct_range_clause.html", "struct_range_clause" ],
    [ "ReportMsg", "struct_report_msg.html", "struct_report_msg" ],
    [ "Result", "struct_result.html", "struct_result" ],
    [ "SetClause", "struct_set_clause.html", "struct_set_clause" ],
    [ "SQLBigInt", "class_s_q_l_big_int.html", "class_s_q_l_big_int" ],
    [ "SQLDateStruct", "struct_s_q_l_date_struct.html", "struct_s_q_l_date_struct" ],
    [ "SQLDouble", "class_s_q_l_double.html", "class_s_q_l_double" ],
    [ "SQLNull", "class_s_q_l_null.html", "class_s_q_l_null" ],
    [ "SQLNumericStruct", "struct_s_q_l_numeric_struct.html", "struct_s_q_l_numeric_struct" ],
    [ "SQLString", "class_s_q_l_string.html", "class_s_q_l_string" ],
    [ "SQLTimeStamp", "class_s_q_l_time_stamp.html", "class_s_q_l_time_stamp" ],
    [ "SQLTimeStampStruct", "struct_s_q_l_time_stamp_struct.html", "struct_s_q_l_time_stamp_struct" ],
    [ "SQLTimeStruct", "struct_s_q_l_time_struct.html", "struct_s_q_l_time_struct" ],
    [ "SQLTypeID", "struct_s_q_l_type_i_d.html", null ],
    [ "SQLTypeID< SQLBigInt >", "struct_s_q_l_type_i_d_3_01_s_q_l_big_int_01_4.html", null ],
    [ "SQLTypeID< SQLDouble >", "struct_s_q_l_type_i_d_3_01_s_q_l_double_01_4.html", null ],
    [ "SQLTypeID< SQLNull >", "struct_s_q_l_type_i_d_3_01_s_q_l_null_01_4.html", null ],
    [ "SQLTypeID< SQLString >", "struct_s_q_l_type_i_d_3_01_s_q_l_string_01_4.html", null ],
    [ "SQLTypeID< SQLTimeStamp >", "struct_s_q_l_type_i_d_3_01_s_q_l_time_stamp_01_4.html", null ],
    [ "Variadic", "struct_variadic.html", "struct_variadic" ],
    [ "WhereClause", "class_where_clause.html", null ]
];